# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

defaults:
  - _self_
  - env: clutter_table
  - gripper: panda

num_images: 200
id: 0
input_id: "0"
scene_dirs: None

hydra:
  job:
    chdir: False
